language: cpp

# The following gives us Ubuntu 14.04 LTS instead of 12.04 LTS
sudo: required
dist: trusty

install:
  - sudo apt-get update -q
  - sudo apt-get install -y ttf-adf-switzera fonts-texgyre texlive-fonts-recommended
  - sudo apt-get install -y texlive-latex-extra texlive-xetex texlive-bibtex-extra biber

script:
  - make

notifications:
  email: false
